### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by ghost** [Dr-Lecter/BhenchodCMD#1]
## The Problem
The program is written in code that is uncompiled.
## Why this is a problem
It requires VS Code (Visual Studio Code) in order to compile the program. VS Code is quite large and an install can be from 2 to 10 GB. 
## Solution
Someone with VS Code available compiles the files into EXEs that any Windows machine can run and uploads it to a new branch, maybe `complied`?

**Comment by Dr-Lecter** [comment]
The EXE can be found in the /bin/Debug folder, or directly accessed here https://github.com/Dr-Lecter/BhenchodCMD/blob/master/FakeCmd/bin/Debug/FakeCmd.exe

**Comment by ghost** [comment]
oh ok. will note next time.
